version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
