version: 1

before:
  hooks:
    - cd src && go mod tidy

builds:
  - dir: src
    binary: stm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format: tar.gz
    files:
      - README.md
      - LICENSE*
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: colinxr
      name: homebrew-tap
    name: stm
    homepage: "https://github.com/colinxr/shopify-theme-manager"
    description: "Shopify Theme Manager CLI"
    install: |
      bin.install "stm"
    test: |
      system "#{bin}/stm --version"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
