name: Release

on:
  push:
    tags:
      - "v*" # Runs on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # Adjust as needed

      - name: Verify Permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_PAT }} # Use the new token
        run: |
          echo "GITHUB_TOKEN permissions:"
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets \
          | jq '.total_count'
          echo "\nHOMEBREW_TAP_GITHUB_TOKEN permissions:"
          curl -s -H "Authorization: Bearer $HOMEBREW_TAP_GITHUB_TOKEN" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets \
          | jq '.total_count'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          install-only: true

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_PAT }} # Use the new token
        run: |
          goreleaser release --clean
