name: Release

on:
  push:
    tags:
      - "v*" # Runs on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # Adjust as needed

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          install-only: true

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_PAT }} # Use the new token
        run: |
          goreleaser release --clean
